warsztatSamochodowy/Controllers/WorkerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;


using warsztatSamochodowy.Forms;
using warsztatSamochodowy.Security;
using warsztatSamochodowy.Models;
using warsztatSamochodowy.Repository;
using System.Text;
using warsztatSamochodowy.Utils;

namespace warsztatSamochodowy.Controllers
{
    [Authorize(Roles = "worker")]
    public class WorkerController : Controller
    {

        ActionRepository actionRepository = new ActionRepository();
        ProposalRepository proposalRepository = new ProposalRepository();
        private List<Proposal> proposalsForWorker = new List<Proposal>();

        public IActionResult Index()
        {
            string? idnetifierString = User.Claims.Where(c => c.Type == CustomClaims.Identifier)
                .Select(c => c.Value).SingleOrDefault();

            if (idnetifierString == null)
            {
                return RedirectToAction("Logout", "Login");
            }

            int id = Int32.Parse(idnetifierString);



            var proposals = proposalRepository.GetProposalByWorker(id);            
            return View(proposals);
        }


        private string buildHeader(Models.Action action)
        {
            StringBuilder headerSb = new StringBuilder();


            if (action?.Proposal?.Vehicle != null)
            {
                headerSb.Append(action.Proposal.Vehicle.RegNumber);
                headerSb.Append(" - ");
            }
            if(action?.ActionType != null)
            {
                headerSb.Append(action.ActionType.Name);
                headerSb.Append(" - ");
            }
            if (action?.Proposal != null)
            {
                headerSb.Append(action.Description);
            }

            return headerSb.ToString();
        }



        public IActionResult BrowseAction(int id)
        {
            var action = actionRepository.GetActionById(id);

            return View(action);
        }

        [HttpGet]
        public IActionResult SetFinal(int id)
        {
            var action = actionRepository.GetActionById(id);

            if(action.Status == StatusEnum.CANCELED|| action.Status == StatusEnum.FINAL)
            {
                return View("BrowseAction", action);
            }

            ViewData["Header"] = buildHeader(action);

            return View(new ActionSetFinalForm(action));
        }

        [HttpPost]
        public IActionResult SetFinal(ActionSetFinalForm form)
        {
            var action = actionRepository.GetActionById(form.Id);



            action.EndDate = DateTime.Now;
            action.Result = form.ResultText;
            actionRepository.Update(action);
            action = actionRepository.SetActionStatus(form.Id, StatusEnum.FINAL);


            return RedirectToAction("ShowProposal", "ShowProposal", new {proposalId = action.ProposalId });
        }


        [HttpGet]
        public IActionResult SetCancelled(int id)
        {
            
            var action = actionRepository.GetActionById(id);

            if (action.Status == StatusEnum.CANCELED || action.Status == StatusEnum.FINAL)
            {
                return View("BrowseAction", action);
            }
            ViewData["Header"] = buildHeader(action);

            return View(new ActionSetCancelledForm(action));
        }

        [HttpPost]
        public IActionResult SetCancelled(ActionSetCancelledForm form)
        {
            var action = actionRepository.GetActionById(form.Id);

            action.EndDate = DateTime.Now;
            action.Result = form.ResultText;
            actionRepository.Update(action);
            action = actionRepository.SetActionStatus(form.Id, StatusEnum.CANCELED);

            return RedirectToAction("ShowProposal", "ShowProposal", new { proposalId = action.ProposalId });
        }













        [HttpGet("Worker/getProposalActionsComplete")]
        public string getProposalActionsComplete(int proposalId)
        {
            List<Models.Action> actions = actionRepository.GetActionsForProposal(proposalId);
            float countAll = actions.Count();
            int percent = 0;
            if (countAll != 0)
            {
                float countComplete = 0;
                foreach (var act in actions)
                {
                    if (act.Status == StatusEnum.CANCELED || act.Status == StatusEnum.FINAL)
                    {
                        countComplete++;
                    }
                }

                percent = (int)Math.Round(countComplete * 100 / countAll);
            }
            return percent.ToString() + "%";
        }


        [HttpGet("Worker/getProposalsFilteredBySearch")]
        public IActionResult getProposalsFilteredBySearch(string searching)
        {
            var id = User.Claims.Where(c => c.Type == CustomClaims.Identifier)
                .Select(c => c.Value).SingleOrDefault();

            this.proposalsForWorker = proposalRepository.GetProposalByWorker(Int32.Parse(id));
            if (searching != null)
            {
                List<Proposal> proposalsFiltered = new List<Proposal>();
                foreach (var prop in this.proposalsForWorker)
                {
                    string name = prop.VehicleId + " " + prop.StartDate.ToString();
                    if (name.CaseInsensitiveContains(searching))
                    {
                        proposalsFiltered.Add(prop);
                    }
                }

                return View("Index", proposalsFiltered);
            }
            return View("Index", this.proposalsForWorker);
        }

        [HttpGet("Worker/getProposalsFilteredBySatus")]
        public IActionResult getProposalsFilteredBySatus(int status)
        {
            var id = User.Claims.Where(c => c.Type == CustomClaims.Identifier)
                .Select(c => c.Value).SingleOrDefault();

            this.proposalsForWorker = proposalRepository.GetProposalByWorker(Int32.Parse(id));
            List<Proposal> proposalsFiltered = new List<Proposal>();
            foreach (var prop in this.proposalsForWorker)
            {
                if ((int)prop.Status == status)
                {
                    proposalsFiltered.Add(prop);
                }
            }
            return View("Index", proposalsFiltered);
        }

    }
}

warsztatSamochodowy/Views/Worker/BrowseAction.cshtml
@model warsztatSamochodowy.Models.Action

@{
    ViewData["Title"] = "BrowseAction";
}

<h1>Opis Zadania</h1>

<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SequenceNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SequenceNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Proposal.VehicleId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Proposal.VehicleId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ActionType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ActionType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Proposal)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Proposal.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Result)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Result)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>

    </dl>
</div>
<div>
    <a asp-action="Index">Lista</a>
    <a asp-action="SetFinal" asp-route-id="@Model.Id">Realizuj</a> |
    <a asp-action="SetCancelled" asp-route-id="@Model.Id">Anuluj</a> ||

</div>

warsztatSamochodowy/Views/Worker/Index.cshtml
@model IEnumerable<warsztatSamochodowy.Models.Proposal>

@{
    ViewData["Title"] = "Index";
}

@using System.Net.Http
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="/css/ManagerZlecenia.css" rel="stylesheet" />
    <link href="/css/ManagerPojazdy.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <!--<script src="~/lib/jquery/dist/jquery.min.js"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <script src="/js/site.js"></script>
    <script src="https://kit.fontawesome.com/b99e675b6e.js"></script>
    <script src="/js/ManagerPojazdy.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/tableexport.jquery.plugin/tableExport.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/bootstrap-table-locale-all.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table@1.18.3/dist/extensions/export/bootstrap-table-export.min.js"></script>
</head>

<div class="flex-center">
    <a type="submit" class="h2" asp-controller="Worker" asp-action="Index" style="text-decoration: none;">Lista zleceń</a>
</div>
<form asp-controller="Worker" asp-action="getProposalsFilteredBySearch" method="get">
    <div class="search_wrap search_wrap_4">
        <div class="search_box">
            <button class="btn btn_common" type="submit">
                <i class="fas fa-search"></i>
            </button>
            <input type="text" class="input input-font-dark" name="searching" placeholder="szukaj...">
        </div>
    </div>
</form>

<div class="flex-center">
    <div class="sorting-container">
        <form asp-controller="Worker" asp-action="getProposalsFilteredBySatus" method="get" class="flex-center">
            <div>
                <button type="submit" class="btn round-button btn-margin btn-blue" name="status" value=0>
                    przyjęte
                </button>
            </div>


            <div>
                <button type="submit" class="btn round-button btn-yellow btn-margin" name="status" value=1>
                    Trwające
                </button>
            </div>

            <div>
                <button type="submit" class="btn round-button btn-green btn-margin" name="status" value=2>
                    Zakończone
                </button>
            </div>

            <div>
                <button type="submit" class="btn round-button btn-red btn-margin" name="status" value=3>
                    Anulowane
                </button>
            </div>
        </form>

    </div>
</div>
<br />

<div class="row d-flex justify-content-center" style="width:100% !important">
    <div class="overflow-auto" style="width:100%; max-height:500px; max-width:9000px; margin: 0 auto">
        <div class="table-container">
            <div class="col-md-8" style="width:900px !important; margin-left:5%">
                <div class="card-hover-shadow-2x mb-3 card">
                    <div class="card-header">
                        <div class="text-capitalize font-weight-normal">Lista twoich zleceń</div>
                    </div>
                    <div class="scroll-area-sm">
                        <perfect-scrollbar class="ps-show-limits">
                            <div style="position: static;" class="ps ps--active-y">
                                <div class="ps-content">
                                    <ul class=" list-group list-group-flush">
                                        @foreach (var item in Model)
                                        {
                                            <li class="list-group-item">
                                                <div class="bg-warning"></div>
                                                <div class="p-0">
                                                    <div class="row">
                                                        <div class="zlecenie-header">
                                                            <form asp-controller="ShowProposal" asp-action="ShowProposal" method="get">
                                                                <button class="h5 a-anim nav-link btn-table" name="proposalId" value="@item.Id">@item.VehicleId @item.StartDate</button>
                                                            </form>
                                                            <i>@item.Description</i>
                                                        </div>
                                                        <div class="progess-container">
                                                            @{
                                                                var uri = new Uri("https://localhost:44323/Proposals/getProposalActionsComplete?proposalId=" + item.Id);

                                                                var cookies = Context.Request.Cookies[".AspNetCore.Cookies"];

                                                                HttpClientHandler handler = new HttpClientHandler();
                                                                handler.CookieContainer = new System.Net.CookieContainer();
                                                                handler.CookieContainer.Add(uri, new System.Net.Cookie(".AspNetCore.Cookies", cookies));

                                                                var clinet = new HttpClient(handler);

                                                                clinet.DefaultRequestHeaders.Add(".AspNetCore.Cookies", cookies);

                                                                var response = await clinet.GetAsync(uri);
                                                                string textResult = await response.Content.ReadAsStringAsync();



                                                                if (@item.Status == StatusEnum.OPEN)
                                                                {
                                                                    <span class="circle circle-blue" data-toggle="tooltip" data-placement="right" title="przyjęte"></span>
                                                                }
                                                                else if (@item.Status == StatusEnum.PROCESSING)
                                                                {
                                                                    <div class="pudelko progress">
                                                                        <div data-percentage="0%" style="width: @textResult;" class="progress-bar progress-bar-success" role="progressbar" aria-valuemin="0" aria-valuemax="100"></div>

                                                                    </div>
                                                                    <span class="circle circle-yellow" data-toggle="tooltip" data-placement="right" title="trwające"></span>
                                                                }
                                                                else if (@item.Status == StatusEnum.FINAL)
                                                                {
                                                                    <span class="circle circle-green" data-toggle="tooltip" data-placement="right" title="zakończone"></span>
                                                                }
                                                                else
                                                                {
                                                                    <span class="circle circle-red" data-toggle="tooltip" data-placement="right" title="anulowane"></span>
                                                                }
                                                            }
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </perfect-scrollbar>
                    </div>
                </div>
            </div>
        </div>
        </div>
    </div>





        @{
            async Task<string> httpRequest(string url)
            {
                var uri = new Uri(url);

                var cookies = Context.Request.Cookies[".AspNetCore.Cookies"];

                HttpClientHandler handler = new HttpClientHandler();
                handler.CookieContainer = new System.Net.CookieContainer();
                handler.CookieContainer.Add(uri, new System.Net.Cookie(".AspNetCore.Cookies", cookies));

                var clinet = new HttpClient(handler);

                clinet.DefaultRequestHeaders.Add(".AspNetCore.Cookies", cookies);

                var response = await clinet.GetAsync(uri);
                string textResult = await response.Content.ReadAsStringAsync();

                return textResult;
            }

        }

warsztatSamochodowy/Views/Worker/SetCancelled.cshtml
@model warsztatSamochodowy.Forms.ActionSetCancelledForm

@{
    ViewData["Title"] = "SetCancelled";
}

<link href="/css/ManagerZlecenia.css" rel="stylesheet" />

<h1>Anuluj</h1>

<h3>@ViewData["Header"]</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SetCancelled">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <h2>Wpisz rezultat</h2>
                <textarea asp-for="ResultText" class="form-control"></textarea>
                <span asp-validation-for="ResultText" class="text-danger"></span>
            </div>
            <br />
            <button class="btn btn-blue" type="submit">Realizuj</button>
        </form>
    </div>
</div>

<div>
    <br />
    <form asp-controller="Action" asp-action="editAction" method="get">
        <button class="btn btn-green" name="actionId" value="@Model.Id" type="submit">Powrót</button>
    </form>
    <br />


</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

warsztatSamochodowy/Views/Worker/SetFinal.cshtml
@model warsztatSamochodowy.Forms.ActionSetFinalForm

@{
    ViewData["Title"] = "SetFinal";
}
<link href="/css/ManagerZlecenia.css" rel="stylesheet" />

<h1>Realizuj</h1>

<h3>@ViewData["Header"]</h3>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="SetFinal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <h2>Wpisz rezultat:</h2>
                <textarea asp-for="ResultText" class="form-control"></textarea>
                <span asp-validation-for="ResultText" class="text-danger"></span>
            </div>
            <br />

            <button class="btn btn-blue" type="submit">Realizuj</button>

        </form>
    </div>
</div>

<div>

    
    <br />
    <form asp-controller="Action" asp-action="editAction" method="get">
        <button class="btn btn-green" name="actionId" value="@Model.Id" type="submit">Powrót</button>
    </form>
    <br />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}